import React from 'react'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import Head from 'next/head'



const aboutUs = () => {
  return (
    <div className={`w-screen  min-h-screen lg:pt-[130px] pt-[85px] text-gray-300 flex justify-center items-center px-[20px] ${styles.fadeinAnime}`} >
         <Head>
        <title>MIB4u | About us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='lg:w-[65vw] w-full' >
        <h1 className='text-[28px] md:text-[36px] font-bold text-center text-zinc-200 mb-[30px] md:mb-[80px]' >About us</h1>
        <h1 className='text-[20px] font-bold text-zinc-200 mb-4' >MIB4u</h1>
        <p className='text-[15px] text-zinc-500 mb-4' >
          MIB4u Gallery is a fast growing online art gallery, connecting people with art and artists they love. MIB4u Gallery offers a beautiful selection of paintings, drawings, sculpture, design, jewellery and photography in various price ranges. It provides artists from around the world with an expertly curated environment in which to exhibit and sell their work. MIB4u Gallery has various sections:
        </p>
        <p className='text-[15px] text-zinc-500 mb-4' >
          For a very small fee artists may exhibit an art selection of their choice, with the possibility to communicate directly with art lovers. If the artist wishes, it is possible to build a larger profile with links to his/her own website. Our aim is to connect art lovers directly with the artists.
        </p>
        <p className='text-[15px] text-zinc-500 mb-4' >
          It is also possible to let us do the work if you do not wish to spend time on selling your art yourself. Leave it to us. We are specialists in selling art and would be happy to include your work. Our portfolio includes large projects. Our system is transparent: Pay to play and no commissions over sold work. Clear and simple.
        </p>
        <p className='text-[15px] text-zinc-500 mb-4' >
          We are based in the Netherlands, internationally known for its rich art culture, prominent design and expertise. With MIB4u Gallery we are redefining the experience of buying and selling art by making it easy, convenient and welcoming for collectors, art lovers and artists alike.
        </p>

        <Image
          src="/images/about-section.webp"
          width="900"
          height="350"
          alt="About Section Image"
          objectFit='contain'
        />
      </div>
    </div>
  )
}

export default aboutUs